//! A six-format physical fixture. The original three-format fixtures keep
//! their exact components and generated bytes; this opt-in adds new leaves.
use super::*;

pub const PROFILE: &str = "fixture.attention-ffn.require-extra-upstream-marker-v2-prefill";
pub const FORMATS: [&str; 6] = [
    "quantization.gguf.q3-k",
    "quantization.gguf.q4-k",
    "quantization.gguf.q5-k",
    "quantization.gguf.iq3-s",
    "quantization.gguf.iq4-nl",
    "quantization.gguf.iq4-xs",
];
impl Family {
    pub fn extra(kind: AttentionKind) -> Self {
        let mut value = Self::new(kind);
        value.selected = match kind {
            AttentionKind::GatedDelta => UpstreamMarkerV2Profile::GatedDeltaExtraPrefill,
            AttentionKind::Causal => UpstreamMarkerV2Profile::CausalExtraPrefill,
            _ => unreachable!(),
        };
        value
    }
}

pub(super) fn extend_schema(schema: &mut WeightSchema) {
    for tensor in &mut schema.tensors {
        let PhysicalWeightLayout::Composite { parts } = &tensor.physical_layout else {
            continue;
        };
        let old_ids: BTreeSet<_> = parts
            .iter()
            .map(|part| match part.layout.as_ref() {
                PhysicalWeightLayout::Dense { component_id } => component_id.clone(),
                PhysicalWeightLayout::BlockQuantized { blocks, .. } => blocks.component_id.clone(),
                _ => panic!("extra fixture only replaces declared dense/block projection leaves"),
            })
            .collect();
        schema.components.retain(|c| !old_ids.contains(&c.id));
        let banked = tensor.dimensions.len() == 3;
        let rank = tensor.dimensions.len();
        let (banks, outputs, inputs) = (
            if banked { tensor.dimensions[0] } else { 1 },
            tensor.dimensions[rank - 2],
            tensor.dimensions[rank - 1],
        );
        let mut next = Vec::new();
        for bank in 0..banks {
            let mut offset = 0;
            for (part, format, qk, bytes) in [
                (0, "q3-k", 256, 110),
                (1, "q4-k", 256, 144),
                (2, "iq3-s", 256, 110),
                (3, "q5-k", 256, 176),
                (4, "iq4-nl", 32, 18),
                (5, "iq4-xs", 256, 136),
                (6, "dense", 1, 0),
            ] {
                let count = if part == 6 {
                    outputs - offset
                } else {
                    (outputs / 7 / 8) * 8
                };
                assert!(count > 0);
                let quantized = bytes != 0;
                let cid: WeightId = id(format!(
                    "component.extra.{}.{}.{}",
                    tensor.id.as_str(),
                    banks - 1 - bank,
                    6 - part
                ));
                let mut dimensions = vec![count, inputs / qk];
                let mut offsets = vec![offset, 0];
                let mut extents = vec![count, inputs];
                if banked {
                    dimensions.insert(0, 1);
                    offsets.insert(0, bank);
                    extents.insert(0, 1);
                }
                schema.components.push(WeightComponentSpec {
                    id: cid.clone(),
                    role: if quantized {
                        WeightComponentRole::PackedValues
                    } else {
                        WeightComponentRole::Values
                    },
                    external_names: vec![format!("{}.bank{bank}.{format}", tensor.id.as_str())],
                    dimensions,
                    encoding: if quantized {
                        WeightEncoding::BlockQuantized(BlockQuantizationSpec {
                            format_id: id(format!("quantization.gguf.{format}")),
                            logical_values_per_block: u32::try_from(qk).unwrap(),
                            bytes_per_block: bytes,
                        })
                    } else {
                        WeightEncoding::Dense {
                            element_type: ElementType::F16,
                        }
                    },
                    required: true,
                });
                next.push(CompositeWeightPart {
                    layout: Box::new(if quantized {
                        PhysicalWeightLayout::BlockQuantized {
                            blocks: PhysicalWeightComponentBinding::exact_contiguous(cid),
                            block_axis: if banked { 2 } else { 1 },
                            block_padding: PhysicalWeightPadding::Exact,
                        }
                    } else {
                        PhysicalWeightLayout::Dense { component_id: cid }
                    }),
                    logical_offsets: offsets,
                    extents,
                });
                offset += count;
            }
            assert_eq!(offset, outputs);
        }
        tensor.physical_layout = PhysicalWeightLayout::Composite { parts: next };
    }
}

pub struct Weights {
    base: attention_family::Weights,
    extra: BTreeMap<WeightId, Vec<u8>>,
}
impl Weights {
    pub fn new(schema: &WeightSchema) -> Self {
        let is_extra = |c: &WeightComponentSpec| matches!(&c.encoding,WeightEncoding::BlockQuantized(s) if matches!(s.format_id.as_str(),"quantization.gguf.q3-k"|"quantization.gguf.iq3-s"|"quantization.gguf.iq4-nl"));
        let mut base_schema = schema.clone();
        base_schema.components.retain(|c| !is_extra(c));
        let base = attention_family::Weights::new(&base_schema);
        let extra = schema
            .components
            .iter()
            .enumerate()
            .filter(|(_, c)| is_extra(c))
            .map(|(ordinal, c)| {
                let WeightEncoding::BlockQuantized(spec) = &c.encoding else {
                    unreachable!()
                };
                let bytes = (0..c.dimensions.iter().product::<u64>() as usize)
                    .flat_map(|block| {
                        let mut data = (0..spec.bytes_per_block as usize)
                            .map(|i| ((i * 17 + block * 7 + ordinal * 19) % 251) as u8)
                            .collect::<Vec<_>>();
                        let scale_offset = if spec.format_id.as_str() == "quantization.gguf.q3-k" {
                            108
                        } else {
                            0
                        };
                        data[scale_offset..scale_offset + 2]
                            .copy_from_slice(&f16::from_f32(1.0 / 32768.0).to_le_bytes());
                        data
                    })
                    .collect();
                (c.id.clone(), bytes)
            })
            .collect();
        Self { base, extra }
    }
    pub fn set_nonfinite_embedding(&mut self, token: u32) {
        self.base.set_nonfinite_embedding(token)
    }
}
impl WeightComponentSource for Weights {
    fn component<'s>(
        &'s self,
        component: &WeightComponentSpec,
    ) -> Result<WeightComponentPayload<'s>, VNextError> {
        if let Some(bytes) = self.extra.get(&component.id) {
            WeightComponentPayload::new(
                component,
                component.external_names[0].clone(),
                "generated-extra-attention.bin",
                component.dimensions.clone(),
                component.physical_element_type(),
                bytes,
            )
        } else {
            self.base.component(component)
        }
    }
}

#[cfg(test)]
#[path = "extra/tests.rs"]
mod tests;
