//! L0 golden chat-template parity: ferrum's renderer vs HF transformers
//! `apply_chat_template`, byte-for-byte.
//!
//! Fixtures live in `tests/fixtures/chat_template/<model-slug>/` and are
//! generated by `scripts/gen_chat_template_goldens.py` (network + uv
//! required at generation time only; this test reads checked-in files).

use ferrum_server::chat_template::{
    render_chat_prompt_with_model_template_options,
    render_chat_prompt_with_tools_and_model_template, ChatTemplateOptions, ModelChatTemplate,
};
use ferrum_server::openai::{ChatMessage, ChatTool};
use serde::Deserialize;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Deserialize)]
struct Meta {
    model_id: String,
    bos_token: Option<String>,
    eos_token: Option<String>,
    #[serde(default)]
    render_kwargs: RenderKwargs,
    /// Timestamp `strftime_now` was pinned to at generation time
    /// (`%Y-%m-%dT%H:%M:%S`). Templates that date their system prompt
    /// (Mistral-Small-3.2, Llama-3.x) only byte-match when rendered with
    /// the same clock.
    #[serde(default)]
    now: Option<String>,
}

#[derive(Deserialize, Default)]
struct RenderKwargs {
    #[serde(default)]
    enable_thinking: Option<bool>,
}

#[derive(Deserialize)]
struct Case {
    messages: Vec<serde_json::Value>,
    #[serde(default)]
    tools: Option<Vec<ChatTool>>,
}

fn fixture_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/chat_template")
}

#[test]
fn chat_template_goldens_match_transformers() {
    let root = fixture_root();
    let mut model_dirs: Vec<PathBuf> = fs::read_dir(&root)
        .expect("fixture root missing — run scripts/gen_chat_template_goldens.py")
        .filter_map(|e| e.ok().map(|e| e.path()))
        .filter(|p| p.is_dir())
        .collect();
    model_dirs.sort();
    assert!(
        !model_dirs.is_empty(),
        "no chat-template fixtures found under {}",
        root.display()
    );

    let mut failures: Vec<String> = Vec::new();
    let mut checked = 0usize;

    for dir in model_dirs {
        let meta: Meta =
            serde_json::from_str(&fs::read_to_string(dir.join("meta.json")).unwrap()).unwrap();
        let template_src = fs::read_to_string(dir.join("template.jinja")).unwrap();
        let mut template =
            ModelChatTemplate::new(template_src, format!("{} (fixture)", meta.model_id));
        template.bos_token = meta.bos_token.clone();
        template.eos_token = meta.eos_token.clone();
        let options = ChatTemplateOptions {
            enable_thinking: meta.render_kwargs.enable_thinking,
            now_override: meta.now.as_deref().map(|s| {
                chrono::NaiveDateTime::parse_from_str(s, "%Y-%m-%dT%H:%M:%S")
                    .unwrap_or_else(|e| panic!("{}: bad meta.json now {s:?}: {e}", meta.model_id))
            }),
        };

        let cases: BTreeMap<String, Case> =
            serde_json::from_str(&fs::read_to_string(dir.join("cases.json")).unwrap()).unwrap();

        for (name, case) in cases {
            let golden = fs::read_to_string(dir.join(format!("golden_{name}.txt"))).unwrap();
            let messages: Vec<ChatMessage> = case
                .messages
                .iter()
                .map(|m| serde_json::from_value(m.clone()).unwrap())
                .collect();

            let rendered = match &case.tools {
                Some(tools) => render_chat_prompt_with_tools_and_model_template(
                    &messages,
                    &meta.model_id,
                    Some(&template),
                    &options,
                    tools,
                    None,
                    &[],
                    None,
                ),
                None => render_chat_prompt_with_model_template_options(
                    &messages,
                    &meta.model_id,
                    Some(&template),
                    &options,
                ),
            };

            checked += 1;
            match rendered {
                Ok(rendered) if rendered == golden => {}
                Ok(rendered) => failures.push(format!(
                    "{} / {}: MISMATCH\n--- ferrum ---\n{:?}\n--- transformers ---\n{:?}",
                    meta.model_id, name, rendered, golden
                )),
                Err(e) => failures.push(format!("{} / {}: RENDER ERROR: {e}", meta.model_id, name)),
            }
        }
    }

    assert!(
        failures.is_empty(),
        "{} of {} golden cases failed:\n\n{}",
        failures.len(),
        checked,
        failures.join("\n\n")
    );
    assert!(checked >= 20, "expected >= 20 golden cases, got {checked}");
}
