version: '3.8'

services:
  ferrum-infer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ferrum-infer:latest
    container_name: ferrum-infer
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=info
      - MODEL_PATH=/models
      - CACHE_DIR=/cache
    volumes:
      - ./models:/models
      - ./cache:/cache
      - ./config:/config
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
