//! Library API work is not a native launch. Internal kernels, padding and
//! vendor-private scratch are intentionally not claimed by these fields.
use super::*;

#[derive(Debug, Clone, Copy)]
pub struct LibraryApiNumericWorkV1 {
    pub output_elements: u64,
    pub reduction_units_per_output: u64,
}

/// Complete scalar call parameters that remain fixed in a resident graph.
/// Pointer/owner permission still comes from the original physical bindings.
#[derive(Debug, Clone, Copy)]
pub struct LibraryReplayParametersV1<'a> {
    pub fixed_parameters: &'a [u64],
}

impl SelectedCommandCostBuilderV1 {
    /// One compute dispatch denotes one API invocation, never a claim about
    /// the number of native kernels generated by the device library.
    pub fn library_call_with_replay_parameters(
        &mut self,
        algorithm: SelectedAlgorithmClassV1,
        work: LibraryApiNumericWorkV1,
        parameters: LibraryReplayParametersV1<'_>,
    ) -> Result<(), StatisticalEvidenceUnknown> {
        self.guard(|this| {
            if parameters.fixed_parameters.is_empty()
                || parameters.fixed_parameters.len() > 128
                || work.output_elements == 0
                || work.reduction_units_per_output == 0
            {
                return Err(StatisticalEvidenceUnknown::InvalidWork);
            }
            this.check_limit()?;
            let numeric = DeviceNumericWorkV1 {
                logical_units: work.output_elements,
                padded_units: work.output_elements,
                inner_work_units: work
                    .output_elements
                    .checked_mul(work.reduction_units_per_output)
                    .ok_or(StatisticalEvidenceUnknown::Overflow)?,
                ..Default::default()
            };
            AlgorithmWorkKindV1::LibraryCall.validate_work(numeric)?;
            let next = this.work.checked_add(numeric)?;
            number(&mut this.family, 2);
            this.family.update(algorithm.0);
            // Existing independent-row proof covers native compute blocks.
            // A library's private workspace/ordering has no such proof here.
            this.independent = super::super::independent_rows::IndependentRowsDigest::Unavailable;
            if let Some(fixed) = &mut this.replay_fixed_launch {
                number(fixed, 2);
                fixed.update(algorithm.0);
                number(fixed, parameters.fixed_parameters.len() as u64);
                for &parameter in parameters.fixed_parameters {
                    number(fixed, parameter);
                }
                number(fixed, work.output_elements);
                number(fixed, work.reduction_units_per_output);
            }
            this.compute += 1;
            this.work = next;
            if let Some(capture) = &mut this.algorithm_work {
                capture.observe(algorithm, AlgorithmWorkKindV1::LibraryCall, numeric);
            }
            Ok(())
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn selected(rows: u64, scalar: u64) -> SelectedCommandCostEvidenceV1 {
        let mut builder = SelectedCommandCostBuilderV1::new_with_algorithm_work(rows);
        builder
            .library_call_with_replay_parameters(
                SelectedAlgorithmClassV1::library_api("vendor.GemmEx", 1, [1; 32], [2; 32])
                    .unwrap(),
                LibraryApiNumericWorkV1 {
                    output_elements: rows * 64,
                    reduction_units_per_output: 32,
                },
                LibraryReplayParametersV1 {
                    fixed_parameters: &[rows, 64, 32, scalar],
                },
            )
            .unwrap();
        builder.finish().unwrap()
    }

    #[test]
    fn library_api_work_has_no_kernel_grid_and_seals_complete_scalar_parameters() {
        let value = selected(4, 1);
        value.validate_command(4, 1, 0).unwrap();
        let table = value.algorithm_work().unwrap().unwrap();
        table.validate_command(&value).unwrap();
        assert_eq!(table.entries()[0].kind(), AlgorithmWorkKindV1::LibraryCall);
        assert_eq!(value.work().grid_blocks, 0);
        assert_eq!(value.work().inner_work_units, 4 * 64 * 32);
        let template = SelectedReplayAlgorithmTemplateV1::from_selected(&value, 4, 1, 0).unwrap();
        template.validate_binding(&selected(4, 1)).unwrap();
        let changed = selected(4, 2);
        assert_eq!(changed.family_signature(), value.family_signature());
        assert_eq!(changed.work(), value.work());
        assert!(template.validate_binding(&changed).is_err());
        assert!(template.validate_binding(&selected(3, 1)).is_err());
        assert!(AlgorithmWorkKindV1::Kernel
            .validate_work(value.work())
            .is_err());
        let mut forged = value.work();
        forged.grid_blocks = 1;
        assert!(AlgorithmWorkKindV1::LibraryCall
            .validate_work(forged)
            .is_err());
    }

    #[test]
    fn library_api_overflow_and_missing_parameters_are_sticky_without_partial_evidence() {
        for (output, inner, parameters) in [(u64::MAX, 2, &[1][..]), (1, 1, &[][..])] {
            let mut builder = SelectedCommandCostBuilderV1::new_with_algorithm_work(1);
            let algorithm =
                SelectedAlgorithmClassV1::library_api("vendor.GemmEx", 1, [1; 32], [2; 32])
                    .unwrap();
            assert!(builder
                .library_call_with_replay_parameters(
                    algorithm,
                    LibraryApiNumericWorkV1 {
                        output_elements: output,
                        reduction_units_per_output: inner
                    },
                    LibraryReplayParametersV1 {
                        fixed_parameters: parameters
                    }
                )
                .is_err());
            assert!(builder
                .library_call_with_replay_parameters(
                    algorithm,
                    LibraryApiNumericWorkV1 {
                        output_elements: 1,
                        reduction_units_per_output: 1
                    },
                    LibraryReplayParametersV1 {
                        fixed_parameters: &[1]
                    }
                )
                .is_err());
            assert!(builder.finish().is_err());
        }
    }
}
