use super::*;

const ROOT: &str = r#"# Workspace release version; keep this comment.
[workspace]
members = ["crates/a", "crates/b"]

[workspace.package]
version = "0.8.7" # coordinated version
edition = "2021"

[workspace.dependencies]
a = { path = "crates/a", version = "0.8.7" } # internal
renamed_b = { package = "b", path = "crates/b", version = "^0.8.7", default-features = false }
serde = { version = "1.0", features = ["derive"] } # external pin

[workspace.metadata]
historical_release = "0.8.7"
"#;

const A: &str = r#"[package]
name = "a"
version.workspace = true

[dependencies]
renamed_b = { workspace = true }
external = { version = ">=1.0, <2.0", features = ["extras"] }

[build-dependencies]
b_build = { package = "b", path = "../b", version = "=0.8.7" } # build annotation

[dev-dependencies.b_dev]
package = "b"
path = "../b"
version = "~0.8.7" # table dependency annotation

[target.'cfg(unix)'.dependencies]
b_unix = { package = "b", path = "../b", version = "0.8.7" }

[target.'cfg(windows)'.build-dependencies]
b_windows = { package = "b", path = "../b" }

[target.'cfg(unix)'.dev-dependencies]
b_dev_unix = { package = "b", path = "../b", version = "^0.8.6" }

[package.metadata]
changelog = "Released 0.8.7 with a historical dependency b 0.8.7"
"#;

const B: &str = r#"[package]
name = "b"
version = "0.8.7" # explicit coordinated version

[dependencies]
serde = "1.0"
"#;

const LOCK: &str = r#"# Generated by Cargo; preserve commentary.
version = 4

[[package]]
name = "a"
version = "0.8.7"
dependencies = [
 "b 0.8.7", # local reference
 "b 0.8.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "b 0.7.0",
 "serde",
]

[[package]]
name = "b"
version = "0.8.7" # local version

[[package]]
name = "b"
version = "0.8.7"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "same-name-registry-must-remain"

[[package]]
name = "b"
version = "0.7.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "older-registry-must-remain"

[[package]]
name = "serde"
version = "1.0.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "external-must-remain"
"#;

fn members() -> Vec<MemberManifest> {
    vec![
        MemberManifest {
            package_name: "a".into(),
            manifest_path: "crates/a/Cargo.toml".into(),
            text: A.into(),
        },
        MemberManifest {
            package_name: "b".into(),
            manifest_path: "crates/b/Cargo.toml".into(),
            text: B.into(),
        },
    ]
}

fn doc(text: &str) -> DocumentMut {
    text.parse().unwrap()
}

#[test]
fn updates_actual_dependency_locations_and_preserves_unrelated_source() {
    let result = plan_version_update(ROOT, &members(), LOCK, "0.9.0").unwrap();
    assert_eq!(result.previous_version, "0.8.7");
    assert_eq!(result.target_version, "0.9.0");
    let root = doc(&result.workspace_manifest);
    assert_eq!(
        root["workspace"]["package"]["version"].as_str(),
        Some("0.9.0")
    );
    assert_eq!(
        root["workspace"]["dependencies"]["renamed_b"]["version"].as_str(),
        Some("^0.9.0")
    );
    assert_eq!(
        root["workspace"]["dependencies"]["renamed_b"]["package"].as_str(),
        Some("b")
    );
    assert_eq!(
        root["workspace"]["metadata"]["historical_release"].as_str(),
        Some("0.8.7")
    );
    assert!(result
        .workspace_manifest
        .contains("# Workspace release version; keep this comment."));
    assert!(result
        .workspace_manifest
        .contains("version = \"0.9.0\" # coordinated version"));
    assert!(result
        .workspace_manifest
        .contains("serde = { version = \"1.0\", features = [\"derive\"] } # external pin"));
    let a = doc(&result.members[0].text);
    assert_eq!(a["package"]["version"]["workspace"].as_bool(), Some(true));
    assert_eq!(
        a["dependencies"]["renamed_b"]["workspace"].as_bool(),
        Some(true)
    );
    assert_eq!(
        a["build-dependencies"]["b_build"]["version"].as_str(),
        Some("=0.9.0")
    );
    assert_eq!(
        a["dev-dependencies"]["b_dev"]["version"].as_str(),
        Some("~0.9.0")
    );
    assert_eq!(
        a["target"]["cfg(unix)"]["dependencies"]["b_unix"]["version"].as_str(),
        Some("0.9.0")
    );
    assert_eq!(
        a["target"]["cfg(windows)"]["build-dependencies"]["b_windows"]["version"].as_str(),
        Some("0.9.0")
    );
    assert_eq!(
        a["target"]["cfg(unix)"]["dev-dependencies"]["b_dev_unix"]["version"].as_str(),
        Some("^0.9.0")
    );
    assert_eq!(
        a["dependencies"]["external"]["version"].as_str(),
        Some(">=1.0, <2.0")
    );
    assert!(result.members[0].text.contains("# build annotation"));
    assert!(result.members[0]
        .text
        .contains("# table dependency annotation"));
    assert!(result.members[0]
        .text
        .contains("Released 0.8.7 with a historical dependency b 0.8.7"));
    assert_eq!(
        doc(&result.members[1].text)["package"]["version"].as_str(),
        Some("0.9.0")
    );
    assert!(result.members[1]
        .text
        .contains("# explicit coordinated version"));
}

#[test]
fn lock_updates_only_local_package_and_local_disambiguated_references() {
    let result = plan_version_update(ROOT, &members(), LOCK, "0.8.8").unwrap();
    let lock = doc(&result.lockfile);
    let packages = lock["package"].as_array_of_tables().unwrap();
    for package in packages.iter() {
        let name = package["name"].as_str().unwrap();
        let version = package["version"].as_str().unwrap();
        if package.contains_key("source") {
            assert!(version == "0.8.7" || version == "0.7.0" || name == "serde");
        } else {
            assert_eq!(version, "0.8.8");
        }
    }
    let references: Vec<_> = packages
        .iter()
        .find(|package| package["name"].as_str() == Some("a"))
        .unwrap()["dependencies"]
        .as_array()
        .unwrap()
        .iter()
        .map(|value| value.as_str().unwrap())
        .collect();
    assert!(references.contains(&"b 0.8.8"));
    assert!(references.contains(&"b 0.8.7 (registry+https://github.com/rust-lang/crates.io-index)"));
    assert!(references.contains(&"b 0.7.0"));
    assert!(result
        .lockfile
        .contains("checksum = \"same-name-registry-must-remain\""));
    assert!(result.lockfile.contains("# local reference"));
    assert!(result.lockfile.contains("# local version"));
}

#[test]
fn plain_or_tabled_registry_dependencies_with_member_names_are_unchanged() {
    let mut members = members();
    members[0].text = A.replace("external = { version = \">=1.0, <2.0\", features = [\"extras\"] }",
        "external = { version = \">=1.0, <2.0\", features = [\"extras\"] }\nb = \"0.7.0\"\nregistry_b = { package = \"b\", version = \"0.8.7\", registry = \"alternate\" }");
    let result = plan_version_update(ROOT, &members, LOCK, "0.9.0").unwrap();
    let member = doc(&result.members[0].text);
    assert_eq!(member["dependencies"]["b"].as_str(), Some("0.7.0"));
    assert_eq!(
        member["dependencies"]["registry_b"]["version"].as_str(),
        Some("0.8.7")
    );
}

#[test]
fn targets_must_be_formal_and_increase_the_current_version() {
    for version in [
        "0.8.7",
        "0.8.6",
        "0.9.0-rc.1",
        "0.9.0+metadata",
        "v0.9.0",
        "0.9",
    ] {
        assert!(
            plan_version_update(ROOT, &members(), LOCK, version).is_err(),
            "{version}"
        );
    }
    assert!(plan_version_update(ROOT, &members(), LOCK, "1.0.0").is_ok());
}

#[test]
fn inconsistent_member_dependency_or_lock_version_is_not_silently_repaired() {
    let mut inconsistent = members();
    inconsistent[1].text = B.replace("version = \"0.8.7\"", "version = \"0.7.0\"");
    assert!(plan_version_update(ROOT, &inconsistent, LOCK, "0.9.0")
        .unwrap_err()
        .contains("explicit version"));
    let bad_root = ROOT.replace("version = \"^0.8.7\"", "version = \"=0.7.0\"");
    assert!(plan_version_update(&bad_root, &members(), LOCK, "0.9.0")
        .unwrap_err()
        .contains("does not accept current"));
    let bad_lock = LOCK.replacen("version = \"0.8.7\"", "version = \"0.7.0\"", 1);
    assert!(plan_version_update(ROOT, &members(), &bad_lock, "0.9.0")
        .unwrap_err()
        .contains("Cargo.lock local package"));
}

#[test]
fn complex_internal_constraints_fail_while_supported_operators_are_preserved() {
    for constraint in [">=0.8.7, <0.9.0", "0.8", "0.8.*", "*", ">=0.8.7", "~0.8"] {
        let root = ROOT.replace("version = \"^0.8.7\"", &format!("version = {constraint:?}"));
        assert!(
            plan_version_update(&root, &members(), LOCK, "0.9.0")
                .unwrap_err()
                .contains("unsupported coordinated"),
            "{constraint}"
        );
    }
    for (before, after) in [
        ("0.8.7", "0.9.0"),
        ("^0.8.7", "^0.9.0"),
        ("~0.8.7", "~0.9.0"),
        ("=0.8.7", "=0.9.0"),
    ] {
        let root = ROOT.replace("version = \"^0.8.7\"", &format!("version = {before:?}"));
        let result = plan_version_update(&root, &members(), LOCK, "0.9.0").unwrap();
        assert_eq!(
            doc(&result.workspace_manifest)["workspace"]["dependencies"]["renamed_b"]["version"]
                .as_str(),
            Some(after)
        );
    }
}

#[test]
fn metadata_names_paths_and_workspace_inheritance_must_agree() {
    let mut wrong_name = members();
    wrong_name[1].package_name = "different".into();
    assert!(plan_version_update(ROOT, &wrong_name, LOCK, "0.9.0")
        .unwrap_err()
        .contains("disagrees"));
    let wrong_alias = ROOT.replace("package = \"b\", ", "");
    assert!(plan_version_update(&wrong_alias, &members(), LOCK, "0.9.0")
        .unwrap_err()
        .contains("use package for renames"));
    let wrong_path = ROOT.replace("path = \"crates/b\"", "path = \"../other-checkout/b\"");
    assert!(plan_version_update(&wrong_path, &members(), LOCK, "0.9.0").is_err());
    let missing_inherited = ROOT.replace("renamed_b = { package = \"b\", path = \"crates/b\", version = \"^0.8.7\", default-features = false }", "");
    assert!(
        plan_version_update(&missing_inherited, &members(), LOCK, "0.9.0")
            .unwrap_err()
            .contains("absent from workspace.dependencies")
    );
    assert!(plan_version_update(ROOT, &[], LOCK, "0.9.0").is_err());
}

#[test]
fn root_package_member_and_workspace_version_share_one_output_document() {
    let root = r#"[package]
name = "a"
version = "0.8.7" # root package
[workspace]
members = []
[workspace.package]
version = "0.8.7" # inherited coordinate
"#;
    let member = MemberManifest {
        package_name: "a".into(),
        manifest_path: "Cargo.toml".into(),
        text: root.into(),
    };
    let lock = "version = 4\n[[package]]\nname = \"a\"\nversion = \"0.8.7\"\n";
    let result = plan_version_update(root, &[member], lock, "0.8.8").unwrap();
    assert_eq!(result.workspace_manifest, result.members[0].text);
    let result = doc(&result.workspace_manifest);
    assert_eq!(result["package"]["version"].as_str(), Some("0.8.8"));
    assert_eq!(
        result["workspace"]["package"]["version"].as_str(),
        Some("0.8.8")
    );
}

#[test]
fn missing_or_duplicate_local_lock_records_are_errors() {
    let without_local_b = LOCK.replace(
        "[[package]]\nname = \"b\"\nversion = \"0.8.7\" # local version\n",
        "",
    );
    assert!(
        plan_version_update(ROOT, &members(), &without_local_b, "0.9.0")
            .unwrap_err()
            .contains("missing source-less")
    );
    let duplicated = format!("{LOCK}\n[[package]]\nname = \"b\"\nversion = \"0.8.7\"\n");
    assert!(plan_version_update(ROOT, &members(), &duplicated, "0.9.0")
        .unwrap_err()
        .contains("multiple source-less"));
}

#[test]
fn a_target_version_collision_must_not_rebind_an_external_lock_dependency() {
    let lock = LOCK.replace(" \"b 0.7.0\",", " \"b 0.7.0\",\n \"b 0.9.0\",");
    let lock = format!("{lock}\n[[package]]\nname = \"b\"\nversion = \"0.9.0\"\nsource = \"registry+https://github.com/rust-lang/crates.io-index\"\nchecksum = \"target-registry-must-remain\"\n");
    assert!(plan_version_update(ROOT, &members(), &lock, "0.9.0")
        .unwrap_err()
        .contains("would collide with the new local version"));
    // A source-qualified external reference already preserves its identity.
    let qualified = lock.replace(
        " \"b 0.9.0\",",
        " \"b 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)\",",
    );
    let result = plan_version_update(ROOT, &members(), &qualified, "0.9.0").unwrap();
    assert!(result
        .lockfile
        .contains("b 0.9.0 (registry+https://github.com/rust-lang/crates.io-index)"));
}
