#!/usr/bin/env bash
#
# pod_bench.sh — runs the Phase 0 parity bench inside the Vast pod.
#
# Locks GPU clocks, runs scripts/bench_vs_vllm.sh, commits the result
# to a sub-directory under docs/bench/. Wraps everything in timeout so
# a stuck bench doesn't burn the pod's budget.
#
# Output:
#   docs/bench/cuda-rtx4090-<date>-parity/
#     ferrum_report.json
#     vllm_report.json
#     parity.md
#     compare.md           (generated by compare_bench.py)
#     ferrum.log, vllm.log

set -euo pipefail

cd /workspace/ferrum-infer-rs
# shellcheck disable=SC1091
source "$HOME/.cargo/env"
# shellcheck disable=SC1091
source /workspace/vllm-venv/bin/activate
export HF_HOME="${HF_HOME:-/workspace/hf-cache}"

log() { echo "[$(date +%H:%M:%S)] $*" >&2; }

log "▶ GPU lock-down"
sudo scripts/lock_gpu.sh -p 350 -c 2520

# Trap to unlock + kill stragglers on exit.
cleanup() {
    sudo scripts/unlock_gpu.sh 2>&1 || true
    pkill -f "target/release/ferrum serve" 2>/dev/null || true
    pkill -f "vllm serve" 2>/dev/null || true
}
trap cleanup EXIT INT TERM

log "▶ parity bench (qwen3:0.6b, c=1,4,16,32, n_repeats=3)"
# n_repeats=3 minimum for CI; keeps wall-clock at ~25-30 min on 4090.
timeout 3600 scripts/bench_vs_vllm.sh \
    qwen3:0.6b 1,4,16,32 \
    --n-repeats 3 \
    --num-prompts 100 \
    --warmup 10 \
    --slo-ttft 500 --slo-tpot 50 --slo-e2e 30000

# bench_vs_vllm.sh wrote docs/bench/cuda-rtx4090-$(date +%Y-%m-%d)-parity/
RESULT_DIR=$(ls -td docs/bench/cuda-rtx4090-*-parity 2>/dev/null | head -1)
if [ -z "$RESULT_DIR" ]; then
    log "ERROR: no result directory produced"
    exit 1
fi

log "▶ rendering markdown comparison"
python3 scripts/compare_bench.py \
    --label-a ferrum --label-b vllm \
    "$RESULT_DIR/ferrum_report.json" "$RESULT_DIR/vllm_report.json" \
    > "$RESULT_DIR/compare.md"

# Capture key gap metric for the decision point (PLAYBOOK § 8).
RATIO=$(python3 - "$RESULT_DIR" <<'PY'
import glob, json, sys
out_dir = sys.argv[1]
def load(p):
    with open(p) as f:
        text = f.read().strip()
    obj = json.loads(text)
    return [obj] if isinstance(obj, dict) else obj
a = load(f"{out_dir}/ferrum_report.json")
b = load(f"{out_dir}/vllm_report.json")
# Take c=32 cell's output_throughput ratio.
for ra in a:
    if ra.get("concurrency") != 32:
        continue
    for rb in b:
        if rb.get("concurrency") == 32:
            r = ra["output_throughput_tps"]["mean"] / rb["output_throughput_tps"]["mean"]
            print(f"{r:.3f}")
            break
PY
)
log "▶ ferrum/vllm output_throughput ratio @ c=32: $RATIO"

# Stash the ratio for the decision logic.
echo "$RATIO" > "$RESULT_DIR/.ratio_c32"

log "✓ bench complete"
log "  $RESULT_DIR/"
log "    parity.md, ferrum_report.json, vllm_report.json, compare.md"
log ""
log "next on host:"
log "  cd $RESULT_DIR && git add . && git commit -m 'bench: parity report'"
