//! Pre-compiled Triton-rs PTX + metadata embedded as static strings.
//!
//! These PTX files are generated by `tools/regen-triton-ptx.sh` on a
//! Linux+CUDA box that has triton-rs checked out as a sibling repo. The
//! bytes are committed to git so that downstream cargo builds don't need
//! the Triton C++ toolchain.
//!
//! Each kernel exposes a const PTX (text) and META (JSON with kernel name,
//! shared_mem, num_warps, global_scratch_size, profile_scratch_size).
//!
//! Only present when the `triton-kernels` feature is enabled.

#![cfg(feature = "triton-kernels")]
#![allow(dead_code)]

pub mod rms_norm_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/rms_norm_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/rms_norm_f32.json");
}

pub mod residual_add_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/residual_add_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/residual_add_f32.json");
}

pub mod residual_add_inplace_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/residual_add_inplace_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/residual_add_inplace_f32.json");
}

pub mod fused_silu_mul_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/fused_silu_mul_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/fused_silu_mul_f32.json");
}

pub mod fused_add_rms_norm_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/fused_add_rms_norm_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/fused_add_rms_norm_f32.json");
}

pub mod layer_norm_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/layer_norm_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/layer_norm_f32.json");
}

pub mod softmax_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/softmax_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/softmax_f32.json");
}

pub mod gelu_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/gelu_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/gelu_f32.json");
}

pub mod add_bias_f32 {
    pub const PTX: &str = include_str!("../triton_ptx/add_bias_f32.ptx");
    pub const META: &str = include_str!("../triton_ptx/add_bias_f32.json");
}
